### ISSUE TITLE
Sticks instead of wooden sword in Cave map

### ISSUE THREAD

**Issue by AKryukov92** [rubenwardy/capturetheflag#102]
Currenly in the Cave map player gets steel pick, wooden sword and 20 torches on each respawn.
There is also a problem: You can get a lot of ore, but unable to craft a sword for yourself.
I propose: give players steel pick, *3 sticks* (instead of sword), 20 torches on each respawn.

Wooden sword is useless anyway. This way you can easily craft at least stone one or even better.

**Comment by ClobberXD** [comment]
Valuable suggestion - I wish this could be added by ruben asap! :+1:

**Comment by afshaan4** [comment]
Yeah the wooden sword is useless in every map n

**Comment by rubenwardy** [comment]
The initial stuff is defined in the map's .conf file, which is not public currently. I've changed this, the .conf is read every time at the start of every match so no restart is required
