### ISSUE TITLE
There is no known way to vote to skip the match

### ISSUE THREAD

**Issue by ClobberXD** [rubenwardy/capturetheflag#108]
There is the /vote command but we don't have the vote_starter priv anyways... I'm helpless when my team-mate has the flag and goes on a spawn-killing frenzy with his 'aides'.

**Comment by afshaan4** [comment]
We need this, it happens often that someone captures the flag then just spawnkills or hangs around doing nothing.

Sometimes even after they time out they go get it again and continue to spawnkills.

**Comment by rubenwardy** [comment]
this feature was always abused by players - eg, they'd join and immediately start a vote, which would pass due to lack of votes. I could make it score related - eg: more than 3000 required to start a vote, but anyone can vote. For now I'll grant you the vote_starter priv which allows you to use /vote (although I don't know your ingame name, @afshaan4 )

**Comment by afshaan4** [comment]
It's:

caoutiouspotato 

(Spelt wrong, I know)

And clobberXD is ANAND

And I agree with requiring a high score to get the vote priv

**Comment by afshaan4** [comment]
@ClobberXD what do you think?
Should we have a sort of "moderator" system, or would a ranking based on score system work better?

**Comment by Gaara95** [comment]
I think it should only be players above a certain score like 3000

**Comment by ClobberXD** [comment]
@rubenwardy Thank you for granting us the vote_starter priv. Although I feel like that is more of a work-around - a more robust system could be implemented later on that grants the vote_starter prive to all players above a certain score :+1: 

While voting can curb spawn-killing to a certain extent, giving better 'default' weapons can go a long way. Take the cavern map for example - that map has witnessed the least spawn-killing( thanks to the default steel pick), compared to the Bridge and 2Hills. Spawn-killing is still in 'vogue' in the 2Hills map, and I blame apples for the same - they are very helpful when in need, but their potential is obviously being abused for spawn-killing

**Comment by afshaan4** [comment]
spawnkilling isn't the only problem it solved, it also solved the "I'm gonna get the flag then just chill around at my base" problem too, which is what stretches some matches on for *way* too long.


>a more robust system could be implemented later on that grants the vote_starter priv to all players above a certain score

agreed.

**Comment by ClobberXD** [comment]
On second thought, granting this priv to every player above a certain score might pave way for abuse, as not all players who meet the criteria are responsible enough to utilise this priv correctly - unless we come up with a better solution, I say @rubenwardy  grants this priv on a player-to-player basis...

**Comment by ClobberXD** [comment]
Bug-report:
I had started a vote (as my team-mate wouldn't capture the flag) a couple of weeks back, and the match was skipped. But I could see the name-tag (highlighted in red) of that player (who was hoarding the flag in the previous match) **throughout the next match** too.

**Comment by afshaan4** [comment]
has it happened more than once?

It hasn't happened when i had to vote to close a match.

**Comment by ClobberXD** [comment]
I've only voted once as of now - so yes only once. :)
