### ISSUE TITLE
The points awarded for a kill can be better documented for easier comprehension

### ISSUE THREAD

**Issue by ClobberXD** [rubenwardy/capturetheflag#109]
It would be nice to have a README.md for ctf_stats mod that documents the calculation for awarding points for a kill / capturing the flag.

**Comment by afshaan4** [comment]
Yeah right now it's very confusing.

**Comment by AKryukov92** [comment]
Do you really need to understand all those calculations?
I think implementing #72 will be enough.

**Comment by ClobberXD** [comment]
@AKryukov92 It would just be nice to know how the points are actually calculated, for those who are interested...

**Comment by AKryukov92** [comment]
Do you really need all those formulas?
I can list you actions, which reward you more score:
* Perform killing streaks (kills without own death)
* Kill players with high kill/death ratio
* You always get at least some score
* There is max amount of score per kill
* Killing players with wood or stone weapons give you less score than killing players with getter weapons

**Comment by ClobberXD** [comment]
I've finally understood how the score is calculated - but it would still be nice to have an official documentation, as it took me multiple attempts to obtain the actual algorithm from within the lua code...

**Comment by rubenwardy** [comment]
The algorithm is mostly dark magic, and isn't really meant to be read by players

**Comment by afshaan4** [comment]
>The algorithm is mostly dark magic, and isn't really meant to be read by players

XD

True tho, it *could* be abused.

**Comment by ClobberXD** [comment]
Haha! It would be nice if the maximum points obtainable can be increased to 200 tho...
