### ISSUE TITLE
All the random chests strewn across the map can be made team-chests

### ISSUE THREAD

**Issue by ClobberXD** [rubenwardy/capturetheflag#111]
Having team-chests across the map has a couple of benefits:
1.  At present, the team-chest (at base) is utterly insufficient to stow the loot.
2. The team-chest in the base can be a dedicated pro-chest

This is the solution to more team-chests, without giving players the option to craft team-chests themselves, as was suggested in [a post in the Forum Topic](https://forum.minetest.net/viewtopic.php?f=10&t=13157&start=275#p310708)

If implemented, this also eradicates the bug mentioned in Issue #56.

**Comment by afshaan4** [comment]
I think making all the chests around the map team chests isn't a good idea (I occasionally take stuff from chests on the enemies side when i cant find it on my side), instead the main team chest can just be made bigger to solve the problem of not having enough space to store loot.

**Comment by ClobberXD** [comment]
Yes, that is a problem...

**Comment by ClobberXD** [comment]
But team-chests everywhere will encourage players to stash the extra stuff away in the chest closest to them (which isn't possible now), instead of feeling lazy to go all the way back to base and keeping it to themselves (and donating it all to the enemy when killed)

**Comment by afshaan4** [comment]
yeah, you have a point.

**Comment by AKryukov92** [comment]
> But team-chests everywhere will encourage players to stash the extra stuff away in the chest closest to them (which isn't possible now), instead of feeling lazy to go all the way back to base and keeping it to themselves (and donating it all to the enemy when killed)

I don't think it is good change. If you lost your sword in battle and enemy is lazy, then you have some chance to get weapon back. If enemy will put all throphies in the chest, it will be very hard to get them back.

**Comment by ClobberXD** [comment]
That's the point - the game becomes even more challenging! But this also fosters the team-spirit and encourages the players to share  good stuff with their team-mates without having to go to the base, or type a 5-word request using '/t'. Also, it's even more difficult to get a sword if the players don't know English. This will help the players develop a habit of dropping off their extra stuff in a chest nearby...

**Comment by afshaan4** [comment]
This definitely would make the teams act more like *teams* instead of an uncoordinated group of players like now.

**Comment by ClobberXD** [comment]
Yes - true. While the team-chest at base can just be made bigger, this doesn't solve the issue of the players having to come all the way to the base to stow away their extra stuff - what if they had a close call and has only about 1 heart left? It's easier to stash it in a nearby chest and hide somewhere instead of risking their lives, and subsequently their weapons, by going all the way back to their base - even a simple fall would be fatal then!

**Comment by AKryukov92** [comment]
> players having to come all the way to the base to stow away their extra stuff

This is not an issue. It is a part of the game.

If players will be able to immediately hide trophies, then enemy players will have no chance to recover after unfortunate attack. First succesfull attack will be most important in the game. If it was, then winning team just start slaughter on enemy base.
It should not happen.

**Comment by afshaan4** [comment]
Yeah weapon circulation and balance all depends on stealing from the enemy, this would reduce that. I still think it's not the best idea to make all the chests team chests.

**Comment by ClobberXD** [comment]
You do have a point there... :+1: 

I'll close this issue then - thanks you guys.
