### ISSUE TITLE
Invisible glass

### ISSUE THREAD

**Issue by AKryukov92** [rubenwardy/capturetheflag#118]
Currenly, glass has default texture and has properties similar to stone.
I propose to make glass completely invisible.
This allows to make invisible labyrinths and walls around the base to increase its defences.

**Comment by rubenwardy** [comment]
No, this would be too OP

**Comment by AKryukov92** [comment]
I don't quite understand why do you think it would be "too OP".
If you don't like complete invisibility, we can make them more transparent. For example by removing white border on the edges, leaving only white dots on the faces.
