### ISSUE TITLE
Player Awards for good behavior in-game

### ISSUE THREAD

**Issue by ClobberXD** [rubenwardy/capturetheflag#122]
Awarding players with medals, badges, or just more points will encourage better behavior while playing IMO. Rewarding more points to players (per match) who don't go on a spawn-killing spree can definitely curb spawn-killing. The award can be displayed in the /rankings formspec and end-of-the-match scores table.

*EDIT: (This is related to Issue **#17**)*

**Comment by afshaan4** [comment]
I agree, we really need to do something about spawnkilling.

This would help.
