### ISSUE TITLE
Community moderation

### ISSUE THREAD

**Issue by ClobberXD** [rubenwardy/capturetheflag#128]
Handful of well-known, responsible and reliable players associated with the CTF community for a long time, could be **granted _limited_ moderation privs**, which I feel would address various issues more efficiently and would also reduce the burden of the dedicated moderators and the administrator.

**Comment by rubenwardy** [comment]
I've been offering kick/ban privs to certain players that I feel able to trust sufficiently. Did you mean something else by this?

**Comment by ClobberXD** [comment]
Yes - This is exactly what I mean...
