### ISSUE TITLE
Add unfriendly mobs

### ISSUE THREAD

**Issue by farooqkz** [rubenwardy/capturetheflag#134]
Ideas: 
 - They are on neither team
 - They attack anyone
 - They drop some items if they get killed

Another idea which I'm not sure about is implementing special win conditions for them and if those conditions are met, round ends, they win and both teams will lose.

**Comment by afshaan4** [comment]
Nah, I think that is unnecessary

**Comment by farooqkz** [comment]
unnecessary or a bad idea?

**Comment by rubenwardy** [comment]
Adding mobs would increase the networking usage of the server, which it already struggles with. It's also too against the idea of CTF

**Comment by farooqkz** [comment]
Even mobs which just randomly kill players is a bad idea? So I have another one:
Mobs assigned to a team. two examples:
Mr. Monster which just kills any enemy that it sees.
Guard which stays near the base and kills enemies.
This adds some sort of AI to the game.

> Adding mobs would increase the networking usage of the server,

That's not really a problem unless you are going to run this software just on your own server.

> It's also too against the idea of CTF

How unfriendly mobs are against the idea of CTF?

**Comment by afshaan4** [comment]
the idea of CTF is a simple captur the flag game, almost "arcade".
Mobs would come in the way of players, who want to fight each other  and  not "some sort of AI".

and as for network latency, this  game is being used in the capture the flag server which already has network latency and map loading problem, see #100 and #112

**Comment by farooqkz** [comment]
> the idea of CTF is a simple capture the flag game, almost "arcade".
> Mobs would come in the way of players, who want to fight each other and not "some sort of AI".

This was for mobs assigned to a team, or neutral ones?

> and as for network latency, this game is being used in the capture the flag server which already has network latency and map loading problem, see #100 and #112

If the game is going to run *only* on rubenwardy's server, then this is a problem.

**Comment by farooqkz** [comment]
> both would come in the way, and IMO be annoying.

But in my opinion it could be fun when they come in your way.
> the primary purpose is for it to be run on rubenwardy's server. you could always fork it and run it locally with the mobs.

> I'm not going to do any development work which I won't then use. I develop this game for my server to offer an experience to players

right, I thought it's not just for your server.

**Comment by rubenwardy** [comment]
I develop this game to run on my server, I don't care about other servers although they're welcome to run the game
