### ISSUE TITLE
Is a map with village(s) a good idea?

### ISSUE THREAD

**Issue by farooqkz** [rubenwardy/capturetheflag#135]
Something like Minecraft's or one of these:
 - https://github.com/Sokomine/mg_villages
 - https://github.com/minetest-mods/mg
![screenshot_20180329_211017](https://user-images.githubusercontent.com/15038218/38101512-bcc35e96-3395-11e8-9d62-976e69e2b5a4.png)
![screenshot_20180329_210657](https://user-images.githubusercontent.com/15038218/38101514-bd14715a-3395-11e8-8ace-265054f35dba.png)

There could be one village in the center of the map or two for each team.

**Comment by rubenwardy** [comment]
this is already in progress, see the map topic https://forum.minetest.net/viewtopic.php?t=19729

**Comment by farooqkz** [comment]
@rubenwardy So answer to my question is "yes".
