### ISSUE TITLE
Add more tags/topics to the repository

### ISSUE THREAD

**Issue by farooqkz** [rubenwardy/capturetheflag#136]
tags like "ctf-*", etc.

**Comment by ClobberXD** [comment]
Would you care to elaborate?

**Comment by farooqkz** [comment]
About what? topics? https://help.github.com/articles/about-topics/

**Comment by ClobberXD** [comment]
Please add the relevant info to your first post

**Comment by farooqkz** [comment]
the title says enough. What else should I say? If you have any question, ask and I'll add answer to the first post.

**Comment by farooqkz** [comment]
> Add *more* tags/topics to the repository

**Comment by ClobberXD** [comment]
Then why don't you suggest a few of them yourself? Constructive feed-back is very different from downright criticism - don't just point out the problems - but instead, also try to come up with solutions for them :)

**Comment by farooqkz** [comment]
- ctf
 - minetest-ctf
 - capture-the-flag

**Comment by farooqkz** [comment]
@AKryukov92: I don't understand.

**Comment by AKryukov92** [comment]
When one should use those tags?
What is the meaning of those tags?

**Comment by farooqkz** [comment]
https://help.github.com/
Search about topics or tags there.

**Comment by farooqkz** [comment]
Also this doesn't need such a long conversation and days of discussing.
