### ISSUE TITLE
Allow bronze and bronze stuff

### ISSUE THREAD

**Issue by farooqkz** [rubenwardy/capturetheflag#137]

**Comment by AKryukov92** [comment]
It is possible to craft bronze tools in Cave map. Other maps are not supposed to have them.
By the way, bronze sword is no better than steel one.

**Comment by farooqkz** [comment]
@AKryukov92: I could not, how should I craft them?
(I use a copper ingot and an iron ingot)

**Comment by ClobberXD** [comment]
@farooqkz - 8 tin ingots around 1 copper ingot will give you 9 bronze ingots.

And as @AKryukov92 said, bronze is just more durable than steel - IMO only useful for pickaxes, which in turn, is only used in the cavern map to a large extent...

**Comment by farooqkz** [comment]
Thanks, I close this.
