### ISSUE TITLE
Give score to players who build

### ISSUE THREAD

**Issue by farooqkz** [rubenwardy/capturetheflag#145]
There are many players who just build and don't fight much. As far as I know, currently they don't gain score.

**Comment by Gaara95** [comment]
Do you mean the players who build the base, or just build random things, or both?

**Comment by farooqkz** [comment]
Not sure about this, yet.

**Comment by ClobberXD** [comment]
**Only** the base, I hope - building useless structures that don't add to the base's defences are not allowed, since they use up limited resources that could've been used to fortify the base itself.

**Comment by farooqkz** [comment]
@ClobberXD: I don't think so. What about players who build bridge(in the bridge map) or a tower out of base to see incoming enemies? Also the game should count digging(should I open another issue for this one?). for example in the cave map.

**Comment by ClobberXD** [comment]
@farooqkz - I was specifically referring to _useless_ structures - bridges and towers are considered to be a part of the 'base', where base refers to all the player-built structures and fortifications that protect the flag. IMHO, a well-built base defends the flag more than even a dozen decent pros can.

That being said, a wooden house by the lava beach certainly isn't a part of the base, even if it's right next to the flag...

Also, this issue can be renamed and re-worded to fit the general discussion of awarding score to players who contribute to the game by strengthening bases, building strategic structures, etc. The only issue is that there'd be tons of extra things to monitor, for _every_  player - given that this is a pure-PvP server which already can't process the high-intensity actions of more than 30 players already, it might be a little more complicated than just throwing in a couple of scripts to award the players' non-PvP interactions.

**Comment by afshaan4** [comment]
Building fortifications is a loosely defined concept.

 coding to detect it will be super difficult as we would need to detect structures and who built them
 then check if the steucture is useful(how do you even do that without machine learning) and so on

At that point it wouldn't be worth it

**Comment by afshaan4** [comment]
We would need a more rigid set of criteria to separate defences from random houses

**Comment by ClobberXD** [comment]
Even if _all_ the fortifications can't be awarded points, we can easily detect base walls - for the time-being, I suggest awarding points to the flag-base itself, with more points if the walls / roof are thicker, or are made up of stronger materials (wood, gravel, etc.)

**Comment by AKryukov92** [comment]
I usually play builder, but I don't like giving score only for building.
In short:
* Walls can't win the game
* Moats are better than walls

Even if you are busy with fortifications, you need to defend incoming attacks.
If you have good fortifications, it will be easier to kill attackers.
Some stupid walls can make it harder to defend the base.
Keep in mind, that moats on H&L or on Bridge work better than walls.
In Cave you need to make moats and parallel tonnels to counter attacks.
Some attacks are performed by underground tonnel. They can be countered only by moats underneath of the base.

**Comment by farooqkz** [comment]
@ClobberXD I know what are you talking about but I was trying to say that not any building/digging which is out of base is useless. e.g. digging a tunnel in the cave map or building a bridge in the bridge map.

And of course detecting useful buildings does not seem easy. however there could be a relief for example like what ClobberXD said.
