### ISSUE TITLE
Team doors control

### ISSUE THREAD

**Issue by AKryukov92** [rubenwardy/capturetheflag#149]
How exactly should work team doors?
Yesterday I picked up some doors and placed them somewhere in the center of the map.
Immediately after this, I tried to open them, but they stay closed. After some time I have seen that they were opened by member of enemy team.

I expect that team doors placed by member of team A should always be available to members of team A.

**Comment by rubenwardy** [comment]
They are owned by the owner of that side of the map. The issue here is that you were allowed to place it at all

**Comment by ClobberXD** [comment]
> I expect that team doors placed by member of team A should always be available to members of team A.

This is exactly what I've been believing all this time too. A team-door should be **operable only by the team of the placer**, _irrespective of its position in the world_. That's the way a team-door is ideally expected to work IMHO.

**Comment by ClobberXD** [comment]
Or the door itself can be colored red or blue...

**Comment by AKryukov92** [comment]
I think that with new inventory it is very possible to allow "red" team to craft "red" doors and "blue" team to craft "blue" doors, which can be opened only by member of associated team.

**Comment by ClobberXD** [comment]
Yes, I'd love to see colored team-doors too. It would appear as a normal steel door in the inventory and crafting table, but should change color on_place, depending on which team the placer belongs to.
