### ISSUE TITLE
Crafting is unintuitive

### ISSUE THREAD

**Issue by afshaan4** [rubenwardy/capturetheflag#154]
The changes to the crafting grid are super different from every other server, it took me forever to figure out how it works. It makes crafting faster than before though.

I suggest adding a message in the crating tab explaining how to craft stuff.

Also the search bar in the crafting tab is selected by default so if you want to leave the inventory you cant just hit `I` and leave as it starts typing in the search bar, you have to move the mouse over and click somewhere else, this is slow and comes in the way.

I suggest removing the search bar as there is only one page of items or making it "unhighlighted" by default.

**Comment by rubenwardy** [comment]
Escape closes windows

**Comment by AKryukov92** [comment]
I don't think we need search field in the middle. This is not creative game with lots of blocks with different color and shape.

**Comment by afshaan4** [comment]
I agree with removing the search bar
