### ISSUE TITLE
Reducing max_users?

### ISSUE THREAD

**Issue by farooqkz** [rubenwardy/capturetheflag#159]
I think 30 is a bit more than server can handle, how about less players so less load and then better quality?
Because we feel lags a lot.
**Edit:**
I'm not sure about this: I'm not sysadmin or Minetest expert.

**Comment by afshaan4** [comment]
The lag is network lag not server lag
the server can handle 30 players fine

**Comment by farooqkz** [comment]
So @rubenwardy, close this!

**Comment by farooqkz** [comment]
@rubenwardy: How you ever played with 26-30 users playing? Didn't you feel the lag?

**Comment by ClobberXD** [comment]
This is issue is irrelevant to the repository. Please use the [server's forum thread](https://forum.minetest.net/viewtopic.php?f=10&t=13157) for such discussions.

On the other hand, the game could definitely do with some optimization. See #320. Improving performance is on the top of my to-do list.
