### ISSUE TITLE
The name of the team which won is hidden by "joined team" messages

### ISSUE THREAD

**Issue by rubenwardy** [rubenwardy/capturetheflag#16]

**Comment by ObaniGemini** [comment]
Maybe put this not as a chat message, but as an advertising message ?
( Like sentences telling you "Player as the flag ! Kill him !" )

**Comment by rubenwardy** [comment]
Previously, the map took so long to regen that there was a delay between winning and the join flood. I'll either add a few seconds of delay, or I'll post to the chat after the reset. Making new HUD elements or adding states to the top-right is rather fiddly.

**Comment by rubenwardy** [comment]
Fixed by https://github.com/rubenwardy/capturetheflag/commit/a77431fba1f7cbafa8f58313dc3ed8c1db323143
