### ISSUE TITLE
Colorize player names in prize/bounty messages

### ISSUE THREAD

**Issue by farooqkz** [rubenwardy/capturetheflag#161]
Colorize player names in prize messages(The next person to kill....) in the way that shows team of that player.

**Comment by ClobberXD** [comment]
Still not fixed, player's name is randomly highlighted with the opposite team's colour.

**Comment by ClobberXD** [comment]
Fixed by @Gael-de-Sailly in [this commit](https://github.com/rubenwardy/capturetheflag/commit/ead8366790a6a58d16e56516d51e0e13ec9e4240)

Issue can be closed now.
