### ISSUE TITLE
[Bug] Suicide with grenade counts as kill (and death of course)

### ISSUE THREAD

**Issue by ClobberXD** [rubenwardy/capturetheflag#162]
If the player committing suicide has a bounty on their head, they are also **rewarded their own bounty**.

_The question is whether to fix this bug by modifying the **shooter** mod, the **bounties** mod, or **both** (recommended)_.

### Some thoughts for consideration
- Making players immune to their own grenades is too OP and unrealistic.
- Players are still immune to the grenades thrown by their own team; it's unrealistic, but without which we'll be seeing players killing their own team-mates for hogging swords and stealing kills.

**Comment by ClobberXD** [comment]
A grenade is supposed to inflict damage on everyone around them; no point in making the game unrealistic by protecting players from their own grenade...

It's the bounty code that needs to be made more robust.

**Comment by rubenwardy** [comment]
The CTF kill player callback shouldn't be called if the killer is the same as the victim

**Comment by ClobberXD** [comment]
Well, how is this possible then?
