### ISSUE TITLE
Map maker fails to export flag positions

### ISSUE THREAD

**Issue by rubenwardy** [rubenwardy/capturetheflag#170]
Also occasionally thinks you've placed 3/2

**Comment by ClobberXD** [comment]
That count seems to increase every time the flag respawns when I try to dig it. The following code seems to be the culprit:

https://github.com/rubenwardy/capturetheflag/blob/c1fe05b78f197ff4063dbb51e1b375f21c63255a/mods/ctf_map/map_maker.lua#L11-L21

https://github.com/rubenwardy/capturetheflag/blob/c1fe05b78f197ff4063dbb51e1b375f21c63255a/mods/ctf_map/map_maker.lua#L44-L46

`set_node` calls `on_construct` here, which inserts another duplicate entry to the `flag_positions` table. A simple fix would be to check for duplicates before insertion.

**Comment by ClobberXD** [comment]
Fixed; can be closed :)
