### ISSUE TITLE
Choose map / multiple maps

### ISSUE THREAD

**Issue by rubenwardy** [rubenwardy/capturetheflag#18]

**Comment by kilbith** [comment]
I quickly played on CTF-server. IMO the random terrain can make one team slightly more advantaged than the opposing team.

The area shall be perfectly symmetrical for equity and well-designed in terms of strategic paths.

**Comment by ObaniGemini** [comment]
The fact is you have to build your own terrain.
So your link is off-topic : fixed terrain with fixed buildings.

What is special with this capture the flag mode is that youc an build your own paths, buildings and mines.
As Minetest is pretty weak on action-style games, this is a good initiative from CTF to enable building.

This way more a strategical game than an action game, so map balance is not really needed, excepted for really important terrain disadvantages (I didn't saw any I think).

But if you want to work on some better map, it would be cool, the actual one is pretty bad IMO (with mg7, please).

**Comment by rubenwardy** [comment]
![screenshot_2017-11-10_01-53-51](https://user-images.githubusercontent.com/2122943/32639714-0df794fe-c5bd-11e7-81ac-f4a74323e1d8.png)

**Comment by rubenwardy** [comment]
Done!
