### ISSUE TITLE
[Rule Listing] Add 'No All Caps' To Rules

### ISSUE THREAD

**Issue by CLtheman1** [rubenwardy/capturetheflag#192]
When Thomas-S is on and I'm using all caps, he warns me, but it's not in the rules. He "explained" to me that not every rule can be listed in the rules. Well, they should.

Add a bullet point somewhere that says "no all caps" or "caps limit to x words per sentence," that way moderators won't be banning over something that isn't listed in the rules.

**Comment by ClobberXD** [comment]
I don't think this is the place to discuss server rules - We have a [forum topic](https://forum.minetest.net/viewtopic.php?f=10&t=13157) for that.

**Comment by AKryukov92** [comment]
If mods are able to control chat messages, then this issue has technical solution.
It will look like "when more than 50% of message contains capitalized letters, then all letters should be lowercased".
No need for "rules", nor for "punishments".
