### ISSUE TITLE
[Moderator Feature] Make Moderators Select A Ban Reason

### ISSUE THREAD

**Issue by CLtheman1** [rubenwardy/capturetheflag#193]
To keep moderators from abusing, there should be a ban gui that makes them select a ban reason from a list. Moderators shouldn't be able to ban a player for anything that isn't mentioned or touched on in the rules. When a moderator types '/ban username' it should pop up the GUI with a list of ban reasons.

**Comment by rubenwardy** [comment]
CTF (the game) doesn't provide any moderator features

**Comment by CLtheman1** [comment]
Well then make moderator features... And what do you mean "impractical"? Minecraft servers use it all the time! This feature would make sure the moderators aren't able to abuse.

**Comment by ClobberXD** [comment]
It's a miracle moderators can stand in the middle of a battle to kick/ban someone. Having to also go through a formspec is ridiculous and utterly pointless.

All kicks and bans are logged, and if a player feels that a moderator misused their capabilities, they can express the same by posting on the forums, or by sending a PM to the admin.

**Comment by ClobberXD** [comment]
It'd be abused, and even if not, it's an extra step to go through...

**Comment by CLtheman1** [comment]
Then to keep it from being abused, a cooldown should be put on this "moderator mode". It's a step worth taking if the moderator wants to safely perform moderation duties.
