### ISSUE TITLE
Pro chest requirements

### ISSUE THREAD

**Issue by AKryukov92** [rubenwardy/capturetheflag#205]
Currently player needs to get high kill/death ratio and some amount of score to get access to pro chest.
I propose:
* Allow all players to **put** *good items*
* Allow to **get** items only to players, who put some amount of *good items*
* Allow to **put** any item to players, who put some amount of *good items*

List of *good items*:
* Steel/Mese/Diamond sword
* Ammo
* Shotgun
* Rifle
* Mese/Diamond pick
* Apple
* SMG
* Wood planks

I propose this because "pro" players usually don't follow strategy: Attack with average weapons, steal good weapons and put good to chest. And this is annoying. I am trying to weaken enemy while those "pros" just wasting good swords in reckless attack.

**Comment by tidle** [comment]
good idea, i'll try to implement it

**Comment by Thomas--S** [comment]
Actually, I prefer the current solution.

**Comment by ClobberXD** [comment]
@AKryukov92 I'm not sure if this is a good idea, or at least one that offers significant improvement w/ respect to the current implementation. It's not as easy as allowing everyone who put good stuff to take good stuff from the chest. We'll have to wait and see if this actually works better. I'm neutral.

**Comment by AKryukov92** [comment]
If you think that it is easier to make "allow everyone who put good stuff to take good stuff", then I am agree with it. It sounds simpler and encourages correct behavior.
