### ISSUE TITLE
Pick up dropped items?

### ISSUE THREAD

**Issue by rubenwardy** [rubenwardy/capturetheflag#21]

**Comment by ObaniGemini** [comment]
Sure it would be faster to take items on the ground with it, but also it would disable the user to take items on high floors. Also, it would surely create lags when breaking tons of blocks at the same time.

#####BUT :

Most of the features I talked about here are dued to the way the mod uses the feature. I think it would be possible just to enable the drops when players die, and not in some other ways (breaking a node, disabling way to take objects by clicking on them).
But still, be carefull with your server's power ;)

**Comment by rubenwardy** [comment]
If I was to do this, blocks would still be snapped straight into the players inventory. Only items dropped on player death or by Q will be picked up. But I think clicking it is fine.

**Comment by ObaniGemini** [comment]
For me, it's a fifty-fifty. You choose :)
