### ISSUE TITLE
Punching player does not deal damage

### ISSUE THREAD

**Issue by AKryukov92** [rubenwardy/capturetheflag#219]
MT version: 0.4.17.1-win64
CTF version 664330276a0f1af3b0d86d4040b8faa5208c1ac7

Steps to reproduce:
1) create game
2) take any weapon
3) attack someone from other team
Victim of punch is expected to lose some health.
Actual: victim health doesn't change.

I did some careful checking and found that reason is the commit b30ea671e43f6fca5b00385ee6ab5c5658aea53d

**Comment by AKryukov92** [comment]
It seems that MT doesn't call function `register_on_punchplayer` at all if "enable_pvp" setting is false.

**Comment by ClobberXD** [comment]
PvP should be enabled for this to work, of course, but #220 is a good idea, since PvP is an essential part of CTF.

**Comment by ClobberXD** [comment]
@AKryukov92 This issue is fixed by #222, so you might want to close it. Please also take a look at https://help.github.com/articles/closing-issues-using-keywords/
