### ISSUE TITLE
Constant healing / health regen

### ISSUE THREAD

**Issue by rubenwardy** [rubenwardy/capturetheflag#28]

**Comment by ObaniGemini** [comment]
https://github.com/BlockMen/hunger

Hunger mod includes constant healing.

**Comment by rubenwardy** [comment]
I won't add the hunger mod, but I may nick some code from it.

**Comment by harrison3000** [comment]
Instead of regenerating health giving the player some apples on spawn may be better...

**Comment by rubenwardy** [comment]
apples can be found in chests now.

**Comment by rubenwardy** [comment]
Apples can now be found in chests. They are the same rarity as ammo.

https://github.com/rubenwardy/capturetheflag/blob/master/mods/ctf_treasure/init.lua#L4

**Comment by rubenwardy** [comment]
36e76e7924fb9b005f9c422e0917e9cb747c0316
