### ISSUE TITLE
Team info is obstructed by minimap

### ISSUE THREAD

**Issue by harrison3000** [rubenwardy/capturetheflag#32]
The team info HUD element is in the same corner as the minimap, so if you have the minimap enabled you cant see which player took your flag etc...
i know the minimap is not that useful yet, but it will be when we have multiple maps...

my sugestion is to move it down just below the minimap...

**Comment by rubenwardy** [comment]
The hud was added before the minimap existed, which is why there is this problem.

**Comment by rubenwardy** [comment]
I'm going to remove the minimap
