### ISSUE TITLE
Armour

### ISSUE THREAD

**Issue by rubenwardy** [rubenwardy/capturetheflag#34]

**Comment by ObaniGemini** [comment]
I don't know if armor would be a really good idea. It would create even more differencies between players with a good stuff and players with no stuff.

**Comment by afshaan4** [comment]
I don't think we need armor, the whole spirit of the game is *short rounds* of CTF adding armor would prolong matches, and IMO remove the thrill in the battles (knowing that you are not invincible)

**Comment by farooqkz** [comment]
How about weak armors like wooden ones?

**Comment by ClobberXD** [comment]
:+1: for closing this issue

**Comment by farooqkz** [comment]
I suggest adding stronger armors for maps which we have strong swords(like the Cave map) and weaker armors or even no armor where we have weaker swords.
