### ISSUE TITLE
Prematch Build Time

### ISSUE THREAD

**Issue by rubenwardy** [rubenwardy/capturetheflag#4]
A barrier to stop players running into no mans land. Damage and PvP disabled.

**Comment by ObaniGemini** [comment]
Mmmh... you should take a look at hungry_games features. https://github.com/MinetestForFun/server-minetestforfun-hungry_games/tree/5be861125e4f2c4123a953c00cb23c3e0a4edd22/mods/hungry_games

Look at the grace period, it's exactly the same princip. But also it would need that the flag spawns at the end of the grace period...
P.S : Search for "grace" in Github search, it will surely make it easier to you
