### ISSUE TITLE
Vote abusing

### ISSUE THREAD

**Issue by rubenwardy** [rubenwardy/capturetheflag#40]
- Limit players to one /vote_next call
  - per match?
  - or per 5 minutes?

**Comment by the1glorfindel** [comment]
I have noticed that some players will /vote_next when their flag is grabbed and they can't stop the grabber...
Rather annoying.

**Comment by Dragonop** [comment]
What about not allowing the match to be ended or skipped if the flag has been grabbed? There could be other problems tho

**Comment by the1glorfindel** [comment]
The only thing I can think of is if no one can get to the person to kill them, and that person can't get back either.
if that is the case they could leave and then join the game to drop it. (unless you can drop the flag manually??)

**Comment by rubenwardy** [comment]
vote has been removed. No real need for it
