### ISSUE TITLE
Add vote and vote_starter to basic_privs

### ISSUE THREAD

**Issue by Dragonop** [rubenwardy/capturetheflag#49]
A priv for /vote that is given to all players, and it being added to the list of privileges that a moderator with basic_privs is able to revoke. This way you can make /vote abusers stop, at least if a moderator is online.

This, or a different privilege that _prevents_ players from voting, that moderators can grant with basic_privs (example: novote)

**Comment by rubenwardy** [comment]
The priv to start a vote is `vote_starter` and the priv to vote in a vote is `vote`.
I don't know how to add a priv to basic_privs :/

**Comment by rubenwardy** [comment]
https://github.com/rubenwardy/capturetheflag/commit/9a8935c3899f69edf72218528f7d67b9fde76dd4

**Comment by rubenwardy** [comment]
It looks like I need to edit builtin, the check is hardcoded: https://github.com/minetest/minetest/blob/master/builtin/game/chatcommands.lua#L185-L187

**Comment by rubenwardy** [comment]
Done. Restart queued.

**Comment by Dragonop** [comment]
Thanks
