### ISSUE TITLE
Segfault when placing blue flag

### ISSUE THREAD

**Issue by shellkr** [rubenwardy/capturetheflag#51]
Minetest crashes when placement of blue flag has the wrong node...

[Read the full crash log](https://ptpb.pw/CfWJ.log)

```
...
...
2016-08-09 22:54:41: INFO[Main]: Connecting to server at 127.0.0.1:51699
2016-08-09 22:54:41: INFO[Main]: Client packetcounter (20):
2016-08-09 22:54:41: INFO[Main]: Client::peerAdded(): peer->id=1
2016-08-09 22:54:41: VERBOSE[Server]: ServerMap: SQLite3 database opened.
[CaptureTheFlag] (flag) blue has wrong node at flag position, ignore, correcting...
[1]    32683 segmentation fault (core dumped)  minetest --verbose > ctf_pvp.log 2>&1
```

If I try to restart the world a couple of times it will eventually start. It also seems to only happen on a newly created world. A world that has existed a while will work.

**Comment by rubenwardy** [comment]
The only thing in that function is a get node and a set node. The segfault is probably elsewhere - a gdb traceback would be useful

**Comment by shellkr** [comment]
Okay, here is the [gdb trace](https://ptpb.pw/9xIc.log)..

...and a short [video](https://ptpb.pw/xPFQ.mkv) of it crashing

**Comment by rubenwardy** [comment]
Those arent traces. Use `bt full` to make a backtrace. You should use a debug build of minetest (`-DCMAKE_BUILD_TYPE=debug` I believe)

**Comment by shellkr** [comment]
I did, actually... but am not running a with debug flags so will try to do that.

**Comment by shellkr** [comment]
hmm.. not sure what I am doing wrong. I compiled a debug version of Minetest from git and then run it through gdb. I gave pretty much the same thing when I use "valley" as world. If I instead use v7 I get [this](https://ptpb.pw/K-_n.log).

**Comment by rubenwardy** [comment]
You need to actually type bt full. What you gave me isn't a stack trace, but is the threads being dumped on a core dump due to sigseg - not helpful at all

**Comment by rubenwardy** [comment]
Oh wait, the second one looks more like it

**Comment by rubenwardy** [comment]
If you remove the map generation limit setting, do you still get this problem?

**Comment by rubenwardy** [comment]
can't reproduce
