### ISSUE TITLE
With dummy player backend, players spawn at 0,0,0 after restart

### ISSUE THREAD

**Issue by rubenwardy** [rubenwardy/capturetheflag#58]

**Comment by asl97** [comment]
Did you mean after server restart?

Is this just for the first few players where the world ain't generated yet or does it persist through the game?

Maybe you can somehow force gen the area when starting using `minetest.emerge_area` and see if it helps.

**Comment by rubenwardy** [comment]
mostly fixed due to auto-starting new game at server start
