### ISSUE TITLE
Fix or Remove Throwing

### ISSUE THREAD

**Issue by rubenwardy** [rubenwardy/capturetheflag#6]

**Comment by rubenwardy** [comment]
Removed for now

**Comment by Ombridride** [comment]
Hi,

I strongly recommend you this throwing mod : https://github.com/MinetestForFun/server-minetestforfun/tree/master/mods/throwing
It's the version used by MinetestForFun-Classic server and we **bugfix/crashfix many things** from the original *throwing_enhanced* mod, we also introduce new **32px textures**, **grant arrows the possibility to hit players**, arrows can fly through grass_*/fire/... and some other non-sens nodes, etc... and many other improves...

You will maybe need  to removed our small "classes" code, and tweka a little the damage done by the bows/arrows, but it's minors tweaks ;) (less than 5 minutes for sure)

List of this mod commits of this mod here : https://github.com/MinetestForFun/server-minetestforfun/commits/master/mods/throwing

**Comment by rubenwardy** [comment]
Added cross bows. The MTF_Classic may also be added at a later point.
