### ISSUE TITLE
Faster Movement

### ISSUE THREAD

**Issue by rubenwardy** [rubenwardy/capturetheflag#7]
```
movement_acceleration_default = 5
movement_acceleration_air = 4
movement_speed_walk = 5
movement_speed_crouch = 2
```

**Comment by ObaniGemini** [comment]
You could add fast as a sprint.

Default value for walk is 
movement_acceleration_default = 3

Default value for fast is 
movement_acceleration_fast = 10
But you could just include it as 1 or 2 values more than movement acceleration

**Comment by rubenwardy** [comment]
not sure, I think this is fine personally. I'd prefer to add sprinting
