### ISSUE TITLE
Teleporting glitch  

### ISSUE THREAD

**Issue by afshaan4** [rubenwardy/capturetheflag#82]
Iv'e noticed that while playing sometimes, I start teleporting randomly, like backwards or forward 5 to 10 blocks.

And this has happens on all the computers i have so I don't think its the client software that is causing the bug.
  
is it just latency on the network?

**Comment by afshaan4** [comment]
i did some tests and found it was my network lag
so the server and my machine had different versions of my location ,thus when they came back in sync i teleported

**Comment by ClobberXD** [comment]
This used to happen to me all the time and I can confirm that this is indeed lag.
