### ISSUE TITLE
Better map

### ISSUE THREAD

**Issue by rubenwardy** [rubenwardy/capturetheflag#9]
- [x] Increasing playing area.
- [x] More trees, less water.

**Comment by ObaniGemini** [comment]
Maybe could we add some schems patterns ?

**Comment by rubenwardy** [comment]
Like buildings? I'd like to have ocassional huts and towers, however most of the buildings should be player made.

**Comment by ObaniGemini** [comment]
@rubenwardy : That was the idea. I should be able to make some little schems of hunts/towers soon.

**Comment by rubenwardy** [comment]
That would be good.
